[phases.setup]
nixPkgs = ["bun", "postgresql_18"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = []

[start]
cmds = """
bun run db:push &&
bun run src/server.ts
"""
